#!/usr/bin/env bash

DEV='/dev/sdf1'
SDF1='/media/sdf1'
FEDORA='/media/sdb3'
DEBIAN='/media/sdc1'

umount "$FEDORA$SDF1"
umount "$DEBIAN$SDF1"
umount "$SDF1"

fsck.ext4 "$DEV"

mount        "$DEV" "$SDF1"
mount --bind "$SDF1" "$DEBIAN$SDF1"
mount --bind "$SDF1" "$FEDORA$SDF1"
