#!/usr/bin/env sh

SETTINGS='/media/sdcard/tofu-data/userdata/xios/root/.config/transmission-daemon/settings.json'
MY_DIR='/root/.kodi'

ln -s /usr/share/zoneinfo/America/Toronto /etc/localtime

mkdir -p /var/spool/cron/crontabs/
crond

(
    crontab -l
    echo '1 4 * * * /opt/local/bin/flexget --cron execute'
) | crontab -

ifconfig wlan0 down &

pkill kodi &

# Force mount missing devices
# [ -d '/opt/' ]        || (mkdir /opt/        && mount /dev/sda1 /opt/) &
[ -d '/media/sdb1/' ] || (mkdir /media/sdb1/ && mount /dev/sdb1 /media/sdb1/) &
[ -d '/media/sdc1/' ] || (mkdir /media/sdc1/ && mount /dev/sdc1 /media/sdc1/) &
[ -d '/media/sdd1/' ] || (mkdir /media/sdd1/ && mount /dev/sdd1 /media/sdd1/) &
[ -d '/media/sde1/' ] || (mkdir /media/sde1/ && mount /dev/sde1 /media/sde1/) &
[ -d '/media/sdf1/' ] || (mkdir /media/sdf1/ && mount /dev/sdf1 /media/sdf1/) &

wait

/opt/sbin/nginx &
#/opt/bin/ushare &

# Initialize NFS server
/opt/sbin/portmap
/opt/sbin/unfsd -e /opt/etc/exports &

# Initialize Samba server
#sed -i 's/log level = 1/log level = 4/' /etc/samba/smb.conf
sed -i '/log file/a\
socket options = TCP_NODELAY IPTOS_LOWDELAY SO_RCVBUF=131072 SO_SNDBUF=131072\
use sendfile = true\
strict allocate = yes\
aio read size = 16384\
aio write size = 16384\
min receivefile size = 16384\
hosts allow = 192.168.0.103 192.168.0.106 192.168.0.150 192.168.0.151 192.168.0.152' /etc/samba/smb.conf &

echo -e '[anime]\npath = /media/sdf1/anime/\navailable = yes\nread only = no\nbrowseable = yes\npublic = yes\nwritable = yes\n\n' >> /etc/samba/smb.conf &
echo -e     '[app]\npath = /media/sdf1/app/\navailable = yes\nread only = no\nbrowseable = yes\npublic = yes\nwritable = yes\n\n' >> /etc/samba/smb.conf &
echo -e '[music]\npath = /media/sdf1/music/\navailable = yes\nread only = no\nbrowseable = yes\npublic = yes\nwritable = yes\n\n' >> /etc/samba/smb.conf &
echo -e       '[tv]\npath = /media/sdf1/tv/\navailable = yes\nread only = no\nbrowseable = yes\npublic = yes\nwritable = yes\n\n' >> /etc/samba/smb.conf &

# Quality of Service workaround. Run in memory to protect storage device and running script from alterations
cp "$MY_DIR"/qos /dev/shm
/dev/shm/qos &
