#!/usr/bin/env sh

SETTINGS='/media/sdcard/tofu-data/userdata/xios/root/.config/transmission-daemon/settings.json'

ln -s /usr/share/zoneinfo/America/Toronto /etc/localtime

mkdir -p /var/spool/cron/crontabs/
crond

(
    crontab -l
    echo -e '0 2 * * * /opt/bin/transmission-daemon'\
          '\n1 2 * * * /opt/local/bin/flexget --cron execute'\
          '\n0 9 * * * /sbin/start-stop-daemon --stop --quiet --retry=TERM/10/KILL/5 --exec /opt/bin/transmission-daemon'
) | crontab -

# Initialize Samba server
echo -e '[torrent]\npath = /opt/torrent/\navailable = yes\nread only = no\nbrowseable = yes\npublic = yes\nwritable = yes\n\n'      >> /etc/samba/smb.conf
echo -e   '[music]\npath = /media/sdb1/music/\navailable = yes\nread only = no\nbrowseable = yes\npublic = yes\nwritable = yes\n\n' >> /etc/samba/smb.conf
echo -e      '[tv]\npath = /media/sdc1/tv/\navailable = yes\nread only = no\nbrowseable = yes\npublic = yes\nwritable = yes\n\n'    >> /etc/samba/smb.conf

sed -i 's/"alt-speed-down": [0-9]*/"alt-speed-down": 0/'                         "$SETTINGS"
sed -i 's/"alt-speed-up": [0-9]*/"alt-speed-up": 0/'                             "$SETTINGS"
sed -i 's/"speed-limit-down": [0-9]*/"speed-limit-down": 250000/'                "$SETTINGS"
sed -i 's/"speed-limit-up": [0-9]*/"speed-limit-up": 250000/'                    "$SETTINGS"
sed -i 's/"speed-limit-down-enabled": false/"speed-limit-down-enabled": true/'   "$SETTINGS"
sed -i 's/"speed-limit-up-enabled": false/"speed-limit-up-enabled": true/'       "$SETTINGS"
sed -i 's/"alt-speed-time-enabled": false/"alt-speed-time-enabled": true/'       "$SETTINGS"
sed -i 's/"alt-speed-time-begin": [0-9]*/"alt-speed-time-begin": 540/'           "$SETTINGS"
sed -i 's/"alt-speed-time-end": [0-9]*/"alt-speed-time-end": 120/'               "$SETTINGS"
sed -i 's/"download-dir": "\/root\/Downloads"/"download-dir": "\/opt\/torrent"/' "$SETTINGS"

ifconfig wlan0 down

pkill kodi

